### ISSUE TITLE
move parse_it package into a src/ directory

### ISSUE THREAD

**Issue by ThomasWaldmann** [naorlivne/parse_it#10]
that makes sure you are actually testing the package / files that got installed and not just the stuff that happens to be in cwd right now.

most coders start without using a `src/` layout and later will migrate to use one. you can save some pain by doing it early.

https://github.com/pypa/packaging.python.org/issues/320

**Comment by naorlivne** [comment]
Reread the link in your suggestion and it seems that there is no consensus for `src` folder.

Personally I see the case it protects about but as there is no official recommendation of how to resolve that potential mistake I'm going to agree with the reason @theacodes closed pypa/packaging.python.org#320 and will only move to src/ directory after there's a Python community consensus of it being the way to go.

**Comment by ThomasWaldmann** [comment]
I didn't see good arguments against the src/-layout (but I've seen good arguments for it, brought up by long-term and experienced python developers).

But I agree that the long discussion there and no formal recommendation / documentation is not helpful.

Consensus is not the most important thing. If you take enough people, there will rarely be total consensus.

So the point is taking the better way.

**Comment by naorlivne** [comment]
Python is a huge community & like most huge community projects there are formal ways of introducing changes to it, in Python this is via PEP which despite the community size has introduced multiple major changes in recent years.

There may be cases where the formal way is too old fashioned & counter productive where I would agree that going against it is for the better but I don't see /src as being one of those cases (it's not that big of an issue IMHO).

Currently there is no PEP accepted or considered regarding making the /src folder the formal\recommended way of doing things so I'm going to stick the to the current way, if\when the formal way changes so too will parse_it.
