### ISSUE TITLE
Read the config from the remote server

### ISSUE THREAD

**Issue by lookcat** [naorlivne/parse_it#111]
## Expected/Wanted Behavior

I read the config file from the nacos server, the config is str type , can you add parse the str config with json. yaml .

## Actual Behavior

````
import json
import yaml
from parse_it import ParseIt

config = """
{'db': [{'mysql': {'username': 'root',  'password': '123456', 'host': '127.0.0.1', 'port': 3306}}]}
"""

config = """
spring:
  application:
    name: server
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        dashboard: http://localhost:8080
"""

try:
    config_1 = json.load(config)
except Exception as e:
    config_1 = yaml.safe_load(config)

print(type(config_1))


class QueryChainWithDict(dict):
    def __init__(self, obj):
        self.obj = obj
 
    def get(self, key):
        return self.obj.get(key)
test_query_chain = QueryChainWithDict(config_1)

print(test_query_chain.get('spring').get('application').get('name'))
    

````

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

Python version: 
(3.6 & higher required, lower versions may work but will not be tested against)
3.9

parse_it version:

OS type & version:
mac os big sur

**Comment by naorlivne** [comment]
Hi @lookcat 

I'm not sure I understand the request, can you clear things up?

**Comment by lookcat** [comment]
> Hi @lookcat
> 
> I'm not sure I understand the request, can you clear things up?

1. the remote server support many configuration file format (json, yaml, yml ...)
2. I fetch the config from the remote server, the server give  a str type content(maybe be json format, yaml format...) to me
3. I don't care about the config content format, when the parse_it could to parse the str content.
4. I  hope that parse_it has chain function to get  content value with the keyword.

**Comment by naorlivne** [comment]
OK got what you meant but unfrtonatly this isn't within parse_it capabilities  currently, parse_it was designed to read from files of multiple types, envvars & cli args, remote servers that you read from and then pass as strings is outside the scope of it.

Gonna close this as it's out of scope.
