### ISSUE TITLE
Advanced parsing bash style

### ISSUE THREAD

**Issue by sayanarijit** [naorlivne/parse_it#16]
I suggest you to take a look at https://github.com/sayanarijit/expandvars
It helps parsing env vars in an advanced way (like bash). It might come in handy in your project.

**Comment by naorlivne** [comment]
Thanks for the suggestion but (and correct me if I'm wrong) I see that as a potentially confusing addition in certain use cases:

Consider the use case of a user that gives priority to JSON over envvars with the following JSON file:

```
{"HOME": "/my_home_folder", "MY_PATH": "$HOME/test"}
```
said user also has a `HOME` envvar defined to point to `/home/user`

if I understand expandvars correctly it will mean that the `MY_PATH` setting of said user will expand to `/home/user/test` where do to him giving priority to JSON I would expect it to expend to `my_home_folder/test` which is really confusing.
