### ISSUE TITLE
Question: can this library be used to read k8s secrets mounted as volume files? 

### ISSUE THREAD

**Issue by pdonorio** [naorlivne/parse_it#221]
As per subject, I couldn't see an obvious way to support the use case 
of secrets that are mounted as files from k8s inside the pod where I'm running code with parse_it:
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume

How it may look like:
- "secrets" is an option like "env" or "json" to be set in the reading order
- you can specify which folder mount secrets
- all upper case files are secrets that match their file name

Thanks for any support/idea,
I really like this library!

**Comment by naorlivne** [comment]
Hi, 

The short answer is it's out of scope, however I have to wonder why your not just mounting the secrets as envvars? from there `parse_it` will just see them as envvars which it will read

**Comment by pdonorio** [comment]
> I do wonder why your not just mounting the secrets as envvars? from there parse_it will just see them as envvars which it will read

To differentiate normal vars from secret.

> The short answer is it's out of scope

I understand, makes sense.
Thanks for replying!
