### ISSUE TITLE
CLI args nested key names

### ISSUE THREAD

**Issue by kesavkolla** [naorlivne/parse_it#49]
How to give key name for nested properties from CLI?  Currently envvar_divider has a support for environment variables.  Is there similar functionality exists for CLI args?

**Comment by naorlivne** [comment]
Something like: 

```bash
my_script.py --my_nested_arg {"example": {"nested_example": "nested_value"}}
``` 

Then on the script you do something like:

```python
from parse_it import ParseIt

my_nested_arg = parser.read_configuration_variable("my_nested_arg")
```

**Comment by naorlivne** [comment]
@kesavkolla did that answer your question?

**Comment by naorlivne** [comment]
closing as seems answered
