### ISSUE TITLE
GPL might be too restrictive for a library

### ISSUE THREAD

**Issue by ThomasWaldmann** [naorlivne/parse_it#5]
Not sure whether you have considered that the GPL is a very restrictive license if used for a library like `parse_it`, see there:

https://en.wikipedia.org/wiki/GPL_linking_exception

Maybe LGPL or an even more free BSD-/MIT-/Python-style license would be more appropriate and might help your project to get more widely used (and get more contributions).

**Comment by naorlivne** [comment]
I admit to not being an expert in the different licenses so you might very well be right but I'm going to hold off on changing the license type until I got a better understanding of the differences between the options.

**Comment by naorlivne** [comment]
Changed to LGPL v3 at 0.6.0 after reading more about it and agreeing that it fits better for a library.
