### ISSUE TITLE
add python version specifiers to pypi metadata

### ISSUE THREAD

**Issue by ThomasWaldmann** [naorlivne/parse_it#7]
as you already test on multiple python versions, you could actually declare that in `setup.py`.

```
Programming Language :: Python
Programming Language :: Python :: 3
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
Programming Language :: Python :: 3.7
```

https://pypi.org/pypi?%3Aaction=list_classifiers

**Comment by naorlivne** [comment]
Good idea, Now the question is what about versions that should work in theory but I'm not testing on as they require the optional `typing` package installed (for instance 3.4)? is there any standard on if those should or should not be included?

**Comment by ThomasWaldmann** [comment]
Well, a lot of projects are currently dropping py34 support anyway, so guess you can just specify py35+.

**Comment by naorlivne** [comment]
Added to 0.5.10
