### ISSUE TITLE
Wrong estimation of type

### ISSUE THREAD

**Issue by pdonorio** [naorlivne/parse_it#70]
Hello there, I'm using this awesome library in all my project,
but today I've hit a strange behavior, that looks like a bug to me.

I'm using in a yaml file a dictionary of unique strings like:
```
0201d9a59b5e
020103fea000
0201c6285571
```

One of them, `020198015e97` gets read like a float.
The workaround is to use `type_estimate=False` when creating the instance, but the estimations comes handy quite often and I don't feel like this one should be read as a number.

## Expected/Wanted Behavior
```python
In [1]: from parse_it import ParseIt
   ...: import os
   ...: os.environ["TEST"] = "020198015e97"
   ...: parser = ParseIt()
   ...: parser.read_configuration_variable("TEST")
Out[1]: "020198015e97"
```

## Actual Behavior
```python
In [1]: from parse_it import ParseIt
   ...: import os
   ...: os.environ["TEST"] = "020198015e97"
   ...: parser = ParseIt()
   ...: parser.read_configuration_variable("TEST")
Out[1]: 2.0198015e+104
```

## Specifications

Python version: 
3.8.2

parse_it version:
parse-it==3.4.0

OS type & version:
latest alpine linux in docker

THANK YOU!

**Comment by naorlivne** [comment]
I think I see what's going on here as `020198015e97` is also a valid float number, for instance it will also persist in this case in python with no packages at all:

```
>>> x = 020198015e97
>>> print(x)
2.0198015e+104
>>> print(type(x))
<class 'float'>
```

So in this case you have a string that is also a valid float, and as the estimator can't know which of them you desire I'm forced on making some assumptions here, one of them is that all floats/ints are also valid strings I assume that if something matching a int/float/etc you want to return that rather then the string (which is the default if noting else is returned).

Unfortunately I don't see any way around making some assumptions of which a user will prefer when an input can be multiple types (for instance I also assume users will prefer `int` over `float` where all `int` are of course also valid `float`)

If you have any ideas on how to better improve the estimation logic I'm always glad for improvements but personally I don't really see how so gonna close this ticket (feel free to reopen it if you have a suggestion).|

Glad you use `parse_it` though, always nice to see something you wrote get used.

**Comment by pdonorio** [comment]
Thanks for pointing out that also python can see it as a float number with out the strings.

As far as I've always known, the scientific `e` notation needs both the dot and the e, just like [those examples in wikipedia](https://en.wikipedia.org/wiki/Scientific_notation#E_notation), but `¯\_(ツ)_/¯` 

I'll figure out another way of reading that list, thanks!
