### ISSUE TITLE
Write or update config file

### ISSUE THREAD

**Issue by HamzaAnis** [naorlivne/parse_it#74]
### Feature request

It would be really great feature to write the updated config to the file as it is done in the [viper](https://github.com/spf13/viper) over [here](https://github.com/spf13/viper/blob/13df72109047b6ae9c907bce81e327265d6d8a9c/viper.go#L1409).

Thank you.

**Comment by naorlivne** [comment]
My intial hunch is that this might be a bit of a future creep as parse_it is only really meant to read configuration options & not set them but could you maybe provide with what use case you had in mind & will see?

**Comment by HamzaAnis** [comment]
Ok let me provide a use case for it so for example you have multiple API keys for the same service in the configuration file like this

```
{
  "apikeys": [{
      "LastUsed": "2019-08-25T04:30:08+05:00",
      "Key": "APIKEY"
    },
    {
      "LastUsed": "2019-08-25T04:28:46+05:00",
      "Key": "APIKEY"
    },
    {
      "LastUsed": "2019-08-25T04:30:14+05:00",
      "Key": "APIKEY"
    }
  ],
  "service": "service name"
}
```
and you have to choose the least recently used key from it and after using it update the last used time tag so in this use case updating the configuration file would be a great future.

**Comment by naorlivne** [comment]
Sorry but I think it will be too feature creep to add this, I mean it will require being able to edit files in multiple formats (JSON,YAML,etc...) and will require an entire logic of "how do you handle multiple files to be edited", and is too out of scope, parse_it is more about reading config into the application rather then setting config so gonna close this as `won't fix`
