### ISSUE TITLE
please tag releases in git

### ISSUE THREAD

**Issue by ThomasWaldmann** [naorlivne/parse_it#8]
https://pypi.org/project/parse-it/#history

you have quite some releases already, but github is not showing them because you never added a git `tag` for them.

if you happen to have a gpg key, you can even sign your tags, so people can verify authenticity.
gpg signing is optional, but nice to have.

**Comment by naorlivne** [comment]
This is actually something I've experimented with a bit before but still haven't nailed down the exact way I want to go about it, right now I'm thinking that the best way will be to have Travis-CI push a tag after a successful build is done, I like it more then having the tag be the trigger for the build as it both ensures that only a build that passes gets tagged in GitHub and seems to be simpler to set up but I'm open to ideas.

Whatever the way will be it will have to be fully automated... manually tagging everytime a build is packaged and released on PyPi is not an option for me.

**Comment by ThomasWaldmann** [comment]
It's quite common that if one does a release 1.2.3 to tag the corresponding changeset also 1.2.3.

Tags (and also releases) should have some meaning, so I guess it is pointless to tag every successful ci build.

Once you have useful release tags, you can save some work by using tools like `setuptools_scm` which automate versioning based on git tags (and also manage the pypi package manifest via committed files).

You can write some scripts automating the tagging and pypi uploading, but the decision when to release has to be manually made because only the release manager can know when it is in a good state for a release and when all milestone items are done, changelog is updated, etc.

**Comment by naorlivne** [comment]
Advancing to new versions will still happen manually by advancing the version number in the setup.py file, that will trigger a new Travis-ci deployment will PyPi which should Ideally also then create the version tag in Github

**Comment by naorlivne** [comment]
Travis will now tag every new release that is the first one to successfully pass the deployment step of it (deployment step of it being the one that pushes the package to pypi) with the same version number as the one it just pushed to PyPi.
